### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by danielballan** [ChrisBeaumont/mpl-modest-image#10]
I see the latest release on PyPI is four years old and does not fully support Python 3. ([This commit](https://github.com/ChrisBeaumont/mpl-modest-image/commit/3f45bc5fe90bac566539affade4e50901a150fc5) was not yet included.) Do you have the time to publish a new release? Let me know if I can help.

**Comment by mrakitin** [comment]
Hello @ChrisBeaumont, any plans to tag the latest version? Also I noticed the critical dependencies of matplotlib and numpy are missing...

**Comment by ChrisBeaumont** [comment]
Hi @danielballan @mrakitin,

I tagged and uploaded a v0.2 to pypi, but don't otherwise have plans to work on this project anymore. Hopefully that's a usable stopgap for you :)

**Comment by mrakitin** [comment]
Thank you, @ChrisBeaumont!
